   [build]
   builder = "NIXPACKS"
   
   [deploy]
   startCommand = "python -m mcp_server_odoo"
   healthcheckPath = "/health"
   healthcheckTimeout = 300
   restartPolicyType = "ON_FAILURE"
   restartPolicyMaxRetries = 10